[workspace]
members = [
  "crates/rari",
  "tools/prepare-binaries",
  "tools/release",
]
resolver = "2"

[workspace.package]
authors = [ "Ryan Skinner" ]
edition = "2024"
license = "MIT"
repository = "https://github.com/rari-build/rari"

[profile.dev.package.num-bigint-dig]
opt-level = 3
