[package]
name = "rari-release"
version = "0.1.0"
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[[bin]]
name = "release"
path = "src/main.rs"

[dependencies]
ratatui = "0.30.0"
crossterm = "0.29.0"
tokio = { version = "1.49.0", features = [
  "full",
  "process"
] }
serde = { version = "1.0.228", features = [ "derive" ] }
serde_json = "1.0.149"
semver = "1.0.27"
anyhow = "1.0.100"
clap = { version = "4.5.54", features = [ "derive" ] }
colored = "3.1.1"
