[package]
name = "rari-release"
version = "0.1.0"
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[[bin]]
name = "release"
path = "src/main.rs"

[dependencies]
ratatui = { workspace = true }
crossterm = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
semver = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
colored = { workspace = true }
regex = { workspace = true }
