[package]
name = "rari-prepare-binaries"
version = "0.1.0"
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[[bin]]
name = "prepare-binaries"
path = "src/main.rs"

[dependencies]
tokio = { version = "1.49.0", features = [
  "full",
  "process"
] }
anyhow = "1.0.100"
clap = { version = "4.5.54", features = [ "derive" ] }
colored = "3.1.1"
